chart:
  repository: ghcr.io/nicklasfrahm-dev/charts

config:
  repository: https://github.com/nicklasfrahm-dev/platform

tenants:
  platform:
    enabled: true
    namespace:
      labels:
        pod-security.kubernetes.io/enforce: privileged
