image:
  repository: "ghcr.io/nicklasfrahm-dev/axon"

expose:
  enabled: true
  hostPrefix: "axon"

env:
  fromLiterals:
    NODE_ENV: production
    AUTH_URL: https://axon.nicklasfrahm.dev
  fromSecrets:
    AUTH_GITHUB_ID:
      axon-secrets: AUTH_GITHUB_ID
    AUTH_GITHUB_SECRET:
      axon-secrets: AUTH_GITHUB_SECRET
    AUTH_SECRET:
      axon-secrets: AUTH_SECRET

probes:
  liveness:
    httpGet:
      path: /
      port: 8080
  readiness:
    httpGet:
      path: /
      port: 8080
  startup:
    httpGet:
      path: /
      port: 8080
