apiVersion: v2
type: application
name: authz
description: Configure roles within the Kubernetes cluster.
icon: https://raw.githubusercontent.com/kubernetes/community/refs/heads/master/icons/png/resources/labeled/sa-256.png
version: 1.0.0
appVersion: "1.0.0"
