cluster: dev-lab01

config:
  repository: https://github.com/nicklasfrahm/cloud

chart:
  repository: ghcr.io/nicklasfrahm/charts

# Each tenant lives in its own namespace.
# By default, there are two tenants:
# - kube-system: for cluster components (e.g., cilium, metrics-server, etc.)
# - platform: for platform components (e.g., cert-manager, external-dns, etc.)
tenants:
  platform:
    enabled: true
  kube-system:
    enabled: true
