apiVersion: v2
name: rook-ceph-cluster
description: A Helm chart to deploy a Rook Ceph Cluster
icon: https://upload.wikimedia.org/wikipedia/commons/0/07/Ceph_Logo_Stacked_RGB.png
type: application
version: 0.1.0
appVersion: "1.18.7"
dependencies:
  - repository: https://charts.rook.io/release
    name: rook-ceph-cluster
    version: 1.18.7
    condition: rook-ceph-cluster.enabled
    tags:
      - storage
      - ceph
      - rook
