{{- if .Values.expose.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "service.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name | quote }}
      {{- if .Values.gateway.namespace }}
      namespace: {{ .Values.gateway.namespace | quote }}
      {{- end }}
  hostnames:
    {{- if .Values.expose.host }}
    - {{ .Values.expose.host | quote }}
    {{- else if .Values.expose.hostPrefix }}
    - {{ printf "%s.%s" .Values.expose.hostPrefix .Values.platform.domain | quote }}
    {{- else }}
    - {{ printf "%s.%s.%s" .Release.Name .Values.platform.location .Values.platform.domain | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: {{ .Values.expose.path.type | quote }}
            value: {{ .Values.expose.path.value | quote }}
      {{- if .Values.expose.path.stripPrefix }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: "/"
      {{- end }}
      backendRefs:
        - name: {{ .Release.Name | quote }}
          port: {{ .Values.service.port }}
{{- end }}
