{{- if .Values.env.fromLiterals }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-env" .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env.fromLiterals }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
