apiVersion: v2
name: rook-ceph
description: A Helm chart for the Rook Ceph Operator
icon: https://upload.wikimedia.org/wikipedia/commons/0/07/Ceph_Logo_Stacked_RGB.png
type: application
version: 0.1.1
appVersion: "1.18.7"
dependencies:
  - repository: https://charts.rook.io/release
    name: rook-ceph
    version: 1.18.7
    condition: rook-ceph.enabled
    tags:
      - storage
      - ceph
      - rook
