apiVersion: v2
name: rook-ceph
description: A Helm chart for the Rook Ceph Operator
type: application
version: 0.1.0
appVersion: "1.18.7"
dependencies:
  - repository: https://charts.rook.io/release
    name: rook-ceph
    version: 1.18.7
    condition: rook-ceph.enabled
    tags:
      - storage
      - ceph
      - rook
