apiVersion: v2
name: gateway-url-redirect
description: Deploy a URL redirect via a Gateway API HTTPRoute.
icon: https://www.kubeblog.com/wp-content/uploads/2024/09/gateway-api-logo-1.png
type: application
version: 1.0.1
appVersion: "1.0.1"
