apiVersion: v2
type: application
name: nvidia-device-plugin
description: Deploy NVIDIA device plugin.
icon: https://www.logo.wine/a/logo/Nvidia/Nvidia-Light-Vertical-Dark-Background-Logo.wine.svg
version: 1.0.0
appVersion: "0.18.0"
dependencies:
  - repository: https://nvidia.github.io/k8s-device-plugin
    name: nvidia-device-plugin
    version: 0.18.0
    condition: nvidia-device-plugin.enabled
    tags:
      - gpu
      - nvidia
      - device-plugin
