cilium:
  gatewayAPI:
    # We are running behind HAProxy and
    # want to preserve the client IP.
    enableProxyProtocol: true
    enableAppProtocol: true
    xffNumTrustedHops: 1

  envoy:
    xffNumTrustedHopsL7PolicyIngress: 1
    xffNumTrustedHopsL7PolicyEgress: 1
