apiVersion: v2
name: kserve
description: |
  A Helm chart to deploy KServe, a Kubernetes-based platform for
  serving machine learning models. KServe provides a standardized
  and scalable way to deploy, manage, and monitor ML models in production.
type: application
icon: https://kserve.github.io/website/img/kserve-logo.png
version: 1.0.0
appVersion: "v0.16.0"
dependencies:
  - repository: oci://ghcr.io/kserve/charts
    name: kserve-crd
    version: v0.16.0
    condition: kserve-crd.enabled
  - repository: oci://ghcr.io/kserve/charts
    name: kserve
    version: v0.16.0
    condition: kserve.enabled
